"""initial migration

Revision ID: 1ac1bb21b00a
Revises: 
Create Date: 2025-03-27 23:21:14.357189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac1bb21b00a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user',
    sa.Column('identity_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('speciality', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='fk_user_role'),
    sa.PrimaryKeyConstraint('identity_number'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment',
    sa.Column('id_app', sa.Integer(), nullable=False),
    sa.Column('identity_number', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('dated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.identity_number'], name='fk_appointment_doctor'),
    sa.ForeignKeyConstraint(['identity_number'], ['user.identity_number'], name='fk_appointment_patient'),
    sa.PrimaryKeyConstraint('id_app')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('offers', sa.String(length=120), nullable=False),
    sa.Column('article', sa.String(length=120), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.identity_number'], name='fk_post_doctor'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('prescription',
    sa.Column('prescrip_id', sa.Integer(), nullable=False),
    sa.Column('identity_number', sa.Integer(), nullable=False),
    sa.Column('left_eye_sph', sa.Float(), nullable=False),
    sa.Column('right_eye_sph', sa.Float(), nullable=False),
    sa.Column('left_eye_cyl', sa.Float(), nullable=False),
    sa.Column('right_eye_cyl', sa.Float(), nullable=False),
    sa.Column('left_eye_axis', sa.Integer(), nullable=False),
    sa.Column('right_eye_axis', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('dated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_number'], ['user.identity_number'], name='fk_prescription_patient'),
    sa.PrimaryKeyConstraint('prescrip_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('identity_number', sa.Integer(), nullable=False),
    sa.Column('prescrip_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lens_type', sa.String(length=50), nullable=False),
    sa.Column('frame_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('dated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_number'], ['user.identity_number'], name='fk_order_patient'),
    sa.ForeignKeyConstraint(['prescrip_id'], ['prescription.prescrip_id'], name='fk_order_prescription'),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('prescription')
    op.drop_table('post')
    op.drop_table('appointment')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
