"""empty message

Revision ID: 48af85257f88
Revises: 
Create Date: 2025-04-11 13:38:16.384125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48af85257f88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('speciality', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_number', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.dni'], name='fk_appointment_doctor'),
    sa.ForeignKeyConstraint(['identity_number'], ['user.dni'], name='fk_appointment_patient'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.dni'], name='fk_comment_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.dni'], name='fk_file_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offers', sa.String(length=120), nullable=False),
    sa.Column('article', sa.String(length=120), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], name='fk_post_doctor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_number', sa.Integer(), nullable=False),
    sa.Column('left_eye_sph', sa.Float(), nullable=False),
    sa.Column('right_eye_sph', sa.Float(), nullable=False),
    sa.Column('left_eye_cyl', sa.Float(), nullable=False),
    sa.Column('right_eye_cyl', sa.Float(), nullable=False),
    sa.Column('left_eye_axis', sa.Integer(), nullable=False),
    sa.Column('right_eye_axis', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('dated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_number'], ['user.dni'], name='fk_prescription_patient'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('identity_number', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lens_type', sa.String(length=50), nullable=False),
    sa.Column('frame_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('dated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_number'], ['user.dni'], name='fk_order_patient'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], name='fk_order_prescription'),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('prescription')
    op.drop_table('post')
    op.drop_table('file_attachment')
    op.drop_table('comment')
    op.drop_table('appointment')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('notification')
    # ### end Alembic commands ###
